import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import React from 'react';
import Header from '@/app/ui/header/header';
import { routing } from '@/app/i18n/routing';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-black antialiased`}>
        <div className="absolute inset-0 h-full bg-[url('/background-main-img.png')] bg-cover">
          <div className='absolute inset-0 bg-black opacity-50'></div>{' '}
        </div>
        <div className='relative z-10'>
          <NextIntlClientProvider messages={messages}>
            <Header locale={locale} />
            <main className='text-white'>{children}</main>
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
