import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import React from 'react';
import Header from '@/app/ui/header';
import { Locale } from '@/i18n-config';
import { getDictionary } from '@/app/[lang]/dictionaries';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang);

  return (
    <html lang={(await params).lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black antialiased`}
      >
        <div className="absolute inset-0 h-full bg-[url('/background-main-img.png')] bg-cover">
          <div className='absolute inset-0 bg-black opacity-50'></div>{' '}
        </div>
        <div className='relative z-10'>
          <Header dictionary={dictionary.header} />
          <main className='text-white'>{children}</main>
        </div>
      </body>
    </html>
  );
}
